<table align="center" width=100%>
    <tr>
        <td width="10%">
            <img src="in_class.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                    <b> Inclass-Lab  <br>(Session 3 & 4)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

##  Table of Content

1. **[One Dimensional Array](#1D)**
2. **[Two Dimensional Array](#2D)**
3. **[Stacking](#Stacking)**
4. **[Splitting](#Splitting)**
5. **[For Loop](#loop)**
6. **[Data Structures with Examples](#Data_Structures)**
7. **[Create and Manipulate the DataFrames](#create_manipulate)**
8. **[Sort](#sorting)**
9. **[Rank](#ranking)**

**Import the NumPy library before solving the exercises**

### Let's begin with some hands-on practice exercises

<a id="1D"> </a>
## 1. One Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Create a 1D array of weights of 10 students and retrieve all the weights greater than 68</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the weights given below: (or create your own list)**

    weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

In [ ]:
# type your code here
weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

filtered_weights = list(filter(lambda x: x > 68, weights))

filtered_weights

[74.2, 85, 74, 70.5, 86, 82]

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Write a code to generate 10 random integers between 20 to 40 (Is it possible to generate same random numbers everytime? If yes, describe the function)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [ ]:
# type your code here
import numpy as np

np.random.seed(20) # making the numpy numeric generator to use same hashinh everytime it generates random number

array = np.random.randint(low=20, high=40, size=10) # it generates random integer and gives 1D array as size is given integer

array

array([23, 35, 29, 31, 27, 22, 20, 28, 39, 36])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Write a program to calculate the sum of each column </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below: (or create your own array)**

    A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

In [ ]:
# type your code here
A = [[1,4,8], [5,7,3], [9,14,2]]
print("Given Array: ", A)
result = [0] * len(A)
def sum_by_column():
    for i in range(0, len(A)):
        for j  in range(0, len(A[0])):
            result[i] += A[j][i]

sum_by_column()

print("Sum of Elements by Column: ", result)

Given Array:  [[1, 4, 8], [5, 7, 3], [9, 14, 2]]
Sum of Elements by Column:  [15, 25, 13]

<a id="2D"> </a>
## 2. Two Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Create a 2D numpy array from a 1D array of 20 elements of your choice. Further, subset the first 5 elements from the second element of a resulting 2D array
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [ ]:
# type your code here
array_1D = np.random.randint(low=20, high=40, size=20)

array_2D = array_1D.reshape(2,10)

print("1D array: ", array_1D)
print("2D array: ", array_2D)

print("Subset of 5 elements: ", array_2D[0][1:6])

1D array:  [39 24 32 24 29 30 20 35 35 30 24 23 32 30 22 27 20 31 35 38]
2D array:  [[39 24 32 24 29 30 20 35 35 30]
 [24 23 32 30 22 27 20 31 35 38]]
Subset of 5 elements:  [24 32 24 29 30]

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Write a program to find BMI of the patients whose height and weight is provided in the list given below
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    list of weights (in kg)
    weights = [57, 69, 54, 65 ,71, 62, 56]

    list of heights (in m)<br>
    heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53]

In [ ]:
# type your code here
weights = [57, 69, 54, 65 ,71, 62, 56]
heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53]

bmi_list = [weight / height ** 2 for weight, height in zip(weights, heights)]

bmi_list

[22.54657648036074,
 22.53061224489796,
 19.5964581216432,
 21.469150482230148,
 26.397977394408095,
 20.9572742022715,
 23.92242299970097]

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Write a program to add a new column ([5,7]) at the last position in the array given below
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    array1 = [[[3, 4], [8, 2],[5, 9]]]

In [ ]:
# type your code here
array1 = [[[3, 4], [8, 2],[5, 9]]]

array1[0].append([5,7])

print(array1)

[[[3, 4], [8, 2], [5, 9], [5, 7]]]

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Write a program to transpose a matrix
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the matrix given below:**
    
    M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

In [ ]:
# type your code here
M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

def print_matrix(arr):
  for item in arr:
    print(item)

# method 1: using map and zip helpers
transpose_M = list(map(list, zip(*M)))

print("Transpose of matrix with map and zip helpers: ")
print_matrix(transpose_M)

# method 2: using loops by swapping values
def transpose(A):
  print("Before transpose: ")
  print_matrix(A)
  for i in range(0, len(A)):
    for j in range(i, len(A)):
      t = A[i][j]
      A[i][j] = A[j][i]
      A[j][i] = t
  print("After transpose: ")
  print_matrix(A)

transpose(M)

Transpose of matrix with map and zip helpers:
[15, 7, 54, 0]
[17, 42, 3, 87]
[45, 15, 61, 16]
[56, 63, 41, 20]
Before transpose:
[15, 17, 45, 56]
[7, 42, 15, 63]
[54, 3, 61, 41]
[0, 87, 16, 20]
After transpose:
[15, 7, 54, 0]
[17, 42, 3, 87]
[45, 15, 61, 16]
[56, 63, 41, 20]

<a id="Stacking"> </a>
## 3. Stacking

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Write a program to combine the two arrays vertically</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**<br>

    A1 = [[5, 9], [7, 6]]

    A2 = [[8,-7], [0,4]]

Combine the array A2 with A1

In [ ]:
# type your code here
A1 = [[5, 9], [7, 6]]
A2 = [[8,-7], [0,4]]

A1 = np.vstack((A1,A2))

A1

array([[ 5,  9],
       [ 7,  6],
       [ 8, -7],
       [ 0,  4]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Write a code to combine the two arrays horizontally</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**

    A1 = [[-81, 75, 40], [27, 67, 52]]

    A2 = [[15, 54], [39, 56]]

Combine the array A2 with A1

In [21]:
# type your code here
A1 = [[-81, 75, 40], [27, 67, 52]]
A2 = [[15, 54], [39, 56]]

A1 = np.hstack((A1, A2))

A1

array([[-81,  75,  40,  15,  54],
       [ 27,  67,  52,  39,  56]])

<a id="Splitting"> </a>
## 4. Splitting

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Write a program to divide the array into two sub-arrays containing equal number of columns
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]

In [25]:
# type your code here
B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]

np.split(np.array(B), 2,axis=1) # Spliiting horizontally because we cannot split it vertically due to odd no of rows asit gic=ves unequal arrays

[array([[ 8,  7],
        [ 2, -3],
        [ 8,  5]]),
 array([[ 0,  9],
        [ 5, 10],
        [-1,  3]])]

<a id="loop"> </a>
## 5. For Loop

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>11. Write a program to perform one-to-one mapping of the two lists</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below: (or create your own lists)**<br>

    L1 = [45, 67, 56, 71, 54, 62, 56]

    L2 = [21, 52, 64, 10, 49, 74, 26]

In [26]:
# type your code here
L1 = [45, 67, 56, 71, 54, 62, 56]
L2 = [21, 52, 64, 10, 49, 74, 26]

result = {}

for key, value in zip(L1, L2):
  result[key] = value

result

{45: 21, 67: 52, 56: 26, 71: 10, 54: 49, 62: 74}

<a id='Data_Structures'></a>
## 6. Data Structures with Examples:

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>12. Write a program to create a dataframe from list of lists
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the below nested list:**<br>

        data = [['Joy', 21], ['Mia', 15], ['Sam', 14]]

In [27]:
# type your code here
import pandas as pd

data = [['Joy', 21], ['Mia', 15], ['Sam', 14]]

df = pd.DataFrame(data, columns=['Name', 'Age'])

df

  Name  Age
0  Joy   21
1  Mia   15
2  Sam   14

<a id='create_manipulate'></a>
## 7. Create and Manipulate the DataFrames:

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>13. Split the 'Name' column into two separate columns as First_Name and Last_Name </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**

<table>
<tr>
<th>Name</th>
<th>Salary</th>
</tr>
<tr>
<td>Emma Larter</td>
<td>3200</td>
</tr>
<tr>
<td>Mia Junior</td>
<td>4500</td>
</tr>
<tr>
<td>Sophia Depp</td>
<td>3600</td>
</tr>
<tr>
<td>James Smith</td>
<td>5596</td>
</tr>
   
</table>

In [30]:
# type your code here
columns = ["Name", "Salary"]
rows = [["Emma Larter", 3200], ["Mia Junior", 4500], ["Sophia Depp", 3600], ["James Smith", 5596]]

df = pd.DataFrame(rows, columns=columns)

df[["First_Name", "Last_Name"]] = df["Name"].str.split(" ", expand=True)

df

          Name  Salary First_Name Last_Name
0  Emma Larter    3200       Emma    Larter
1   Mia Junior    4500        Mia    Junior
2  Sophia Depp    3600     Sophia      Depp
3  James Smith    5596      James     Smith

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>14. Write a program to select the rows where the sales are higher than 60000 for Mumbai </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [32]:
## Prepare data set
columns = ["Store", "Location", "Sales"]
rows = [["A", "Mumbai", 40000], ["B", "Pune", 45000], ["A", "Hyderabad", 50000],
        ["C", "Mumbai", 90000], ["D", "Pune", 89000], ["A", "Delhi", 87000],
        ["D", "Hyderabad", 85000], ["A", "Pune", 78000], ["C", "Mumbai", 89000],
        ["B", "Pune", 70000]]

df = pd.DataFrame(rows, columns=columns)

df

  Store   Location  Sales
0     A     Mumbai  40000
1     B       Pune  45000
2     A  Hyderabad  50000
3     C     Mumbai  90000
4     D       Pune  89000
5     A      Delhi  87000
6     D  Hyderabad  85000
7     A       Pune  78000
8     C     Mumbai  89000
9     B       Pune  70000

In [33]:
# type your code here
df[(df["Location"] == "Mumbai") & (df["Sales"] > 60000)]

  Store Location  Sales
3     C   Mumbai  90000
8     C   Mumbai  89000

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>15. Write a program to replace the 'Store' column with the values A, B, C, and D with Store_A,  Store_B, Store_C and Store_D respectively </b>  
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [34]:
# type your code here
df["Store"] = ["Store_" + str(val) for val in df["Store"]]
# can be achived with replace method like df["Store"].replace(["A", "B", "C", "D"], ["Store_A", "Store_B", "Store_C", "Store_D"])
# using list comprihension helps even if. we have more diffrent values instead of mentioning them manually
df

     Store   Location  Sales
0  Store_A     Mumbai  40000
1  Store_B       Pune  45000
2  Store_A  Hyderabad  50000
3  Store_C     Mumbai  90000
4  Store_D       Pune  89000
5  Store_A      Delhi  87000
6  Store_D  Hyderabad  85000
7  Store_A       Pune  78000
8  Store_C     Mumbai  89000
9  Store_B       Pune  70000

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>16. Write a program to insert a given column at the second position in a dataframe
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**

<table>
<tr>
<th>Name</th>
<th>Age</th>
</tr>
<tr>
<td>Emma Larter</td>
<td>34</td>
</tr>
<tr>
<td>Mia Junior</td>
<td>59</td>
</tr>
<tr>
<td>Sophia Depp</td>
<td>32</td>
</tr>
<tr>
<td>James Smith</td>
<td>40</td>
</tr>
   
</table>

**Add the variable 'Salary' as second column**<br>
            
            Salary = [35000, 24000, 55000, 40000]

In [35]:
# type your code here
columns = ["Name", "Age"]
rows = [["Emma Larter", 34], ["Mia Junior", 59], ["Sophia Depp", 32], ["James Smith", 40]]

df = pd.DataFrame(rows, columns=columns)

df.insert(1, "Salary", [35000, 24000, 55000, 40000])

df

          Name  Salary  Age
0  Emma Larter   35000   34
1   Mia Junior   24000   59
2  Sophia Depp   55000   32
3  James Smith   40000   40

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>17. Write a program to get the third observation of the given dataframe
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**

<table>
<tr>
<th>Name</th>
<th>Age</th>
</tr>
<tr>
<td>Emma Larter</td>
<td>34</td>
</tr>
<tr>
<td>Mia Junior</td>
<td>59</td>
</tr>
<tr>
<td>Sophia Depp</td>
<td>32</td>
</tr>
<tr>
<td>James Smith</td>
<td>40</td>
</tr>
</table>

In [36]:
# type your code here
df.iloc[2] ## Using the Dataframe the one created previously

Name      Sophia Depp
Salary          55000
Age                32
Name: 2, dtype: object

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>18. Write a program to count total sales per store </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [37]:
# type your code here
columns = ["Store", "Location", "Sales"]
rows = [["A", "Mumbai", 40000], ["B", "Pune", 45000], ["A", "Hyderabad", 50000],
        ["C", "Mumbai", 90000], ["D", "Pune", 89000], ["A", "Delhi", 87000],
        ["D", "Hyderabad", 85000], ["A", "Pune", 78000], ["C", "Mumbai", 89000],
        ["B", "Pune", 70000]]

df = pd.DataFrame(rows, columns=columns)

df.groupby("Store")["Sales"].sum()

Store
A    255000
B    115000
C    179000
D    174000
Name: Sales, dtype: int64

<a id='sorting'></a>
## 8. Sort

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>19. Write a program to sort the dataframe by 'Store' in ascending order and by 'Sales' in descending order simultaneously
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [38]:
# type your code here
df.sort_values(["Store", "Sales"], ascending=[True, False])

  Store   Location  Sales
5     A      Delhi  87000
7     A       Pune  78000
2     A  Hyderabad  50000
0     A     Mumbai  40000
9     B       Pune  70000
1     B       Pune  45000
3     C     Mumbai  90000
8     C     Mumbai  89000
4     D       Pune  89000
6     D  Hyderabad  85000

<a id='ranking'></a>
## 9. Rank

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>20. Rank the dataframe in descending order of sales by each store
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [46]:
# type your code here

df.groupby("Store")["Sales"].rank(ascending=False)

0    4.0
1    2.0
2    3.0
3    1.0
4    1.0
5    1.0
6    2.0
7    2.0
8    2.0
9    1.0
Name: Sales, dtype: float64